version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "npm"
      - "run"
      - "watch"
    env_file:
      - ./src/config/development
    ports:
      - 4000:4000
    volumes:
      - "./src:/app/src"
  postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=koaapp
      - POSTGRES_PASSWORD=nodeapp
      - POSTGRES_DB=koaapp
    ports:
    - 5432:5432